export const GET_ALL_PLANS = 'GET_ALL_PLANS';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS';
export const GET_ALL_BALANCES = 'GET_ALL_BALANCES';
